name: shopping_list_g11
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.3
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.3
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4

  # For OCR
  image_picker: ^1.0.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  google_ml_kit: ^0.19.0
  image: ^4.0.17
  google_mlkit_smart_reply: ^0.12.0

  # For Gemini
  flutter_gemini: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
