enum MeasurementType { amount, liter, gram, milliliter, kilogram }

// Eventuelt konvertere 5000 g til 5 kg f.eks

/// Helper method to convert the types to their corresponding measurement unit.
String getUnitLabel(MeasurementType type) {
  switch (type) {
    case MeasurementType.liter:
      return 'L';
    case MeasurementType.milliliter:
      return 'mL';
    case MeasurementType.gram:
      return 'g';
    case MeasurementType.kilogram:
      return 'kg';
    case MeasurementType.amount:
    default:
      return ''; // countable items have no unit suffix
  }
}
MeasurementType measurementTypeFromString(String s) {
  switch (s.toLowerCase()) {
    case 'l':
    case 'liter':
      return MeasurementType.liter;
    case 'ml':
    case 'milliliter':
      return MeasurementType.milliliter;
    case 'kg':
    case 'kilogram':
      return MeasurementType.kilogram;
    case 'g':
    case 'gram':
      return MeasurementType.gram;
    default:
      return MeasurementType.amount;
  }
}


/// map generated by ChatGPT, with additions from me manually as well.
final Map<String, MeasurementType> groceryMapping = {
  // Fruits
  'apple': MeasurementType.amount,
  'banana': MeasurementType.amount,
  'orange': MeasurementType.amount,
  'pear': MeasurementType.amount,
  'grapes': MeasurementType.amount, // might be sold as bunches ? so 1 is one container
  'strawberry': MeasurementType.gram,
  'blueberry': MeasurementType.gram,
  'watermelon': MeasurementType.amount,

  // Vegetables
  'tomato': MeasurementType.amount,
  'potato': MeasurementType.amount,
  'onion': MeasurementType.amount,
  'carrot': MeasurementType.amount,
  'lettuce': MeasurementType.amount,
  'cucumber': MeasurementType.amount,
  'bell pepper': MeasurementType.amount,
  'broccoli': MeasurementType.amount,
  'spinach': MeasurementType.amount,

  // Dairy
  'milk': MeasurementType.liter,
  'cheese': MeasurementType.gram,
  'yogurt': MeasurementType.amount, // unsure on this one
  'butter': MeasurementType.gram, // this one too
  'cream': MeasurementType.liter,

  // Bakery
  'bread': MeasurementType.amount,
  'bagel': MeasurementType.amount,
  'muffin': MeasurementType.amount,
  'croissant': MeasurementType.amount,
  'donut': MeasurementType.amount,

  // Meat & Seafood
  'beef': MeasurementType.gram,
  'chicken': MeasurementType.gram,
  'pork': MeasurementType.gram,
  'lamb': MeasurementType.gram,
  'fish': MeasurementType.gram,
  'shrimp': MeasurementType.gram,

  // Dry Goods & Grains
  'rice': MeasurementType.gram,
  'pasta': MeasurementType.gram,
  'flour': MeasurementType.gram,
  'sugar': MeasurementType.gram,
  'oats': MeasurementType.gram,
  'cereal': MeasurementType.amount,

  // Beverages
  'juice': MeasurementType.liter,
  'soda': MeasurementType.liter,
  'energy drink': MeasurementType.liter,
  'water': MeasurementType.liter,
  'coffee': MeasurementType.gram, // for beans or ground coffee
  'tea': MeasurementType.amount,  // for tea bags

  // Canned & Jarred Goods
  'canned beans': MeasurementType.amount,
  'canned tomatoes': MeasurementType.amount,
  'soup': MeasurementType.amount,
  'jam': MeasurementType.gram,
  'pickles': MeasurementType.amount,

  // Snacks & Sweets
  'chips': MeasurementType.amount,
  'chocolate bar': MeasurementType.amount,
  'candy': MeasurementType.amount,
  'cookies': MeasurementType.amount,
  'crackers': MeasurementType.amount,

  // Frozen Foods
  'frozen pizza': MeasurementType.amount,
  'ice cream': MeasurementType.liter, // or amount if in single-serving cups, vi må se litt på denne

  // Spices & Condiments
  'salt': MeasurementType.gram,
  'pepper': MeasurementType.gram,
  'ketchup': MeasurementType.liter,
  'mustard': MeasurementType.liter,
  'olive oil': MeasurementType.liter,
  'vinegar': MeasurementType.liter,

  // Household Items & Others
  'toilet paper': MeasurementType.amount, // packs of rolls
  'paper towels': MeasurementType.amount,
  'dish soap': MeasurementType.liter,
  'laundry detergent': MeasurementType.liter,
};
